//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.07.13 at 04:55:54 PM EEST 
//


package com.dkey.customs.soapmeta;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ArrayOfBrokAnalyticsCancellStatusNumbersItem complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ArrayOfBrokAnalyticsCancellStatusNumbersItem"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="BrokAnalyticsCancellStatusNumbersItem" type="{http://tempuri.org/}BrokAnalyticsCancellStatusNumbersItem" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ArrayOfBrokAnalyticsCancellStatusNumbersItem", propOrder = {
    "brokAnalyticsCancellStatusNumbersItem"
})
public class ArrayOfBrokAnalyticsCancellStatusNumbersItem {

    @XmlElement(name = "BrokAnalyticsCancellStatusNumbersItem", nillable = true)
    protected List<BrokAnalyticsCancellStatusNumbersItem> brokAnalyticsCancellStatusNumbersItem;

    /**
     * Gets the value of the brokAnalyticsCancellStatusNumbersItem property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the brokAnalyticsCancellStatusNumbersItem property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getBrokAnalyticsCancellStatusNumbersItem().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link BrokAnalyticsCancellStatusNumbersItem }
     * 
     * 
     */
    public List<BrokAnalyticsCancellStatusNumbersItem> getBrokAnalyticsCancellStatusNumbersItem() {
        if (brokAnalyticsCancellStatusNumbersItem == null) {
            brokAnalyticsCancellStatusNumbersItem = new ArrayList<BrokAnalyticsCancellStatusNumbersItem>();
        }
        return this.brokAnalyticsCancellStatusNumbersItem;
    }

}
