//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.07.13 at 04:55:54 PM EEST 
//


package com.dkey.customs.soapmeta;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for CancellBrokLicByGuidReq complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CancellBrokLicByGuidReq"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://tempuri.org/}CsnWsRequestArgBase"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="LicGuid" type="{http://microsoft.com/wsdl/types/}guid"/&gt;
 *         &lt;element name="Cancelled" type="{http://www.w3.org/2001/XMLSchema}dateTime"/&gt;
 *         &lt;element name="Cancellor" type="{http://www.w3.org/2001/XMLSchema}decimal"/&gt;
 *         &lt;element name="Comment" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="Status" type="{http://www.w3.org/2001/XMLSchema}unsignedByte"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CancellBrokLicByGuidReq", propOrder = {
    "licGuid",
    "cancelled",
    "cancellor",
    "comment",
    "status"
})
public class CancellBrokLicByGuidReq
    extends CsnWsRequestArgBase
{

    @XmlElement(name = "LicGuid", required = true)
    protected String licGuid;
    @XmlElement(name = "Cancelled", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar cancelled;
    @XmlElement(name = "Cancellor", required = true)
    protected BigDecimal cancellor;
    @XmlElement(name = "Comment")
    protected String comment;
    @XmlElement(name = "Status")
    @XmlSchemaType(name = "unsignedByte")
    protected short status;

    /**
     * Gets the value of the licGuid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLicGuid() {
        return licGuid;
    }

    /**
     * Sets the value of the licGuid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLicGuid(String value) {
        this.licGuid = value;
    }

    /**
     * Gets the value of the cancelled property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getCancelled() {
        return cancelled;
    }

    /**
     * Sets the value of the cancelled property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setCancelled(XMLGregorianCalendar value) {
        this.cancelled = value;
    }

    /**
     * Gets the value of the cancellor property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getCancellor() {
        return cancellor;
    }

    /**
     * Sets the value of the cancellor property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setCancellor(BigDecimal value) {
        this.cancellor = value;
    }

    /**
     * Gets the value of the comment property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getComment() {
        return comment;
    }

    /**
     * Sets the value of the comment property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setComment(String value) {
        this.comment = value;
    }

    /**
     * Gets the value of the status property.
     * 
     */
    public short getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     */
    public void setStatus(short value) {
        this.status = value;
    }

}
