//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.07.13 at 04:55:54 PM EEST 
//


package com.dkey.customs.soapmeta;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CancellBrokLicReq complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CancellBrokLicReq"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://tempuri.org/}CsnWsRequestArgBase"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="LicNum" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="Comment" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="Cancellor" type="{http://www.w3.org/2001/XMLSchema}decimal"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CancellBrokLicReq", propOrder = {
    "licNum",
    "comment",
    "cancellor"
})
public class CancellBrokLicReq
    extends CsnWsRequestArgBase
{

    @XmlElement(name = "LicNum")
    protected String licNum;
    @XmlElement(name = "Comment")
    protected String comment;
    @XmlElement(name = "Cancellor", required = true)
    protected BigDecimal cancellor;

    /**
     * Gets the value of the licNum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLicNum() {
        return licNum;
    }

    /**
     * Sets the value of the licNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLicNum(String value) {
        this.licNum = value;
    }

    /**
     * Gets the value of the comment property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getComment() {
        return comment;
    }

    /**
     * Sets the value of the comment property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setComment(String value) {
        this.comment = value;
    }

    /**
     * Gets the value of the cancellor property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getCancellor() {
        return cancellor;
    }

    /**
     * Sets the value of the cancellor property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setCancellor(BigDecimal value) {
        this.cancellor = value;
    }

}
