//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.07.13 at 04:55:54 PM EEST 
//


package com.dkey.customs.soapmeta;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for GetBrokPdfReq complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="GetBrokPdfReq"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://tempuri.org/}CsnWsRequestArgAuth"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="BrokDsXml" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GetBrokPdfReq", propOrder = {
    "brokDsXml"
})
public class GetBrokPdfReq
    extends CsnWsRequestArgAuth
{

    @XmlElement(name = "BrokDsXml")
    protected String brokDsXml;

    /**
     * Gets the value of the brokDsXml property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBrokDsXml() {
        return brokDsXml;
    }

    /**
     * Sets the value of the brokDsXml property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBrokDsXml(String value) {
        this.brokDsXml = value;
    }

}
