//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.07.13 at 04:55:54 PM EEST 
//


package com.dkey.customs.soapmeta;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for GetBrokAnalyticsNumbersReq complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="GetBrokAnalyticsNumbersReq"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://tempuri.org/}CsnWsRequestArgBase"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="DateFrom" type="{http://www.w3.org/2001/XMLSchema}dateTime"/&gt;
 *         &lt;element name="DateTo" type="{http://www.w3.org/2001/XMLSchema}dateTime"/&gt;
 *         &lt;element name="IncludeTotalNumber" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="IncludeIssuedNumber" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="IncludeReissuedNumber" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="IncludeSuspendedNumber" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="IncludeCancelledNumber" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GetBrokAnalyticsNumbersReq", propOrder = {
    "dateFrom",
    "dateTo",
    "includeTotalNumber",
    "includeIssuedNumber",
    "includeReissuedNumber",
    "includeSuspendedNumber",
    "includeCancelledNumber"
})
public class GetBrokAnalyticsNumbersReq
    extends CsnWsRequestArgBase
{

    @XmlElement(name = "DateFrom", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar dateFrom;
    @XmlElement(name = "DateTo", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar dateTo;
    @XmlElement(name = "IncludeTotalNumber")
    protected boolean includeTotalNumber;
    @XmlElement(name = "IncludeIssuedNumber")
    protected boolean includeIssuedNumber;
    @XmlElement(name = "IncludeReissuedNumber")
    protected boolean includeReissuedNumber;
    @XmlElement(name = "IncludeSuspendedNumber")
    protected boolean includeSuspendedNumber;
    @XmlElement(name = "IncludeCancelledNumber")
    protected boolean includeCancelledNumber;

    /**
     * Gets the value of the dateFrom property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDateFrom() {
        return dateFrom;
    }

    /**
     * Sets the value of the dateFrom property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDateFrom(XMLGregorianCalendar value) {
        this.dateFrom = value;
    }

    /**
     * Gets the value of the dateTo property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDateTo() {
        return dateTo;
    }

    /**
     * Sets the value of the dateTo property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDateTo(XMLGregorianCalendar value) {
        this.dateTo = value;
    }

    /**
     * Gets the value of the includeTotalNumber property.
     * 
     */
    public boolean isIncludeTotalNumber() {
        return includeTotalNumber;
    }

    /**
     * Sets the value of the includeTotalNumber property.
     * 
     */
    public void setIncludeTotalNumber(boolean value) {
        this.includeTotalNumber = value;
    }

    /**
     * Gets the value of the includeIssuedNumber property.
     * 
     */
    public boolean isIncludeIssuedNumber() {
        return includeIssuedNumber;
    }

    /**
     * Sets the value of the includeIssuedNumber property.
     * 
     */
    public void setIncludeIssuedNumber(boolean value) {
        this.includeIssuedNumber = value;
    }

    /**
     * Gets the value of the includeReissuedNumber property.
     * 
     */
    public boolean isIncludeReissuedNumber() {
        return includeReissuedNumber;
    }

    /**
     * Sets the value of the includeReissuedNumber property.
     * 
     */
    public void setIncludeReissuedNumber(boolean value) {
        this.includeReissuedNumber = value;
    }

    /**
     * Gets the value of the includeSuspendedNumber property.
     * 
     */
    public boolean isIncludeSuspendedNumber() {
        return includeSuspendedNumber;
    }

    /**
     * Sets the value of the includeSuspendedNumber property.
     * 
     */
    public void setIncludeSuspendedNumber(boolean value) {
        this.includeSuspendedNumber = value;
    }

    /**
     * Gets the value of the includeCancelledNumber property.
     * 
     */
    public boolean isIncludeCancelledNumber() {
        return includeCancelledNumber;
    }

    /**
     * Sets the value of the includeCancelledNumber property.
     * 
     */
    public void setIncludeCancelledNumber(boolean value) {
        this.includeCancelledNumber = value;
    }

}
