//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.07.13 at 04:55:54 PM EEST 
//


package com.dkey.customs.soapmeta;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for GetBrokListReq complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="GetBrokListReq"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://tempuri.org/}CsnWsRequestArgAuth"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="LicNum" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="Date1" type="{http://www.w3.org/2001/XMLSchema}dateTime"/&gt;
 *         &lt;element name="Date2" type="{http://www.w3.org/2001/XMLSchema}dateTime"/&gt;
 *         &lt;element name="ViewDate" type="{http://www.w3.org/2001/XMLSchema}dateTime"/&gt;
 *         &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="Adr" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="Uori" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="Code" type="{http://www.w3.org/2001/XMLSchema}decimal"/&gt;
 *         &lt;element name="Status" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="ResultLimitParam" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="FromOutside" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="IncludeSanctions" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GetBrokListReq", propOrder = {
    "licNum",
    "date1",
    "date2",
    "viewDate",
    "name",
    "adr",
    "uori",
    "code",
    "status",
    "resultLimitParam",
    "fromOutside",
    "includeSanctions"
})
public class GetBrokListReq
    extends CsnWsRequestArgAuth
{

    @XmlElement(name = "LicNum")
    protected String licNum;
    @XmlElement(name = "Date1", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar date1;
    @XmlElement(name = "Date2", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar date2;
    @XmlElement(name = "ViewDate", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar viewDate;
    @XmlElement(name = "Name")
    protected String name;
    @XmlElement(name = "Adr")
    protected String adr;
    @XmlElement(name = "Uori")
    protected String uori;
    @XmlElement(name = "Code", required = true)
    protected BigDecimal code;
    @XmlElement(name = "Status")
    protected String status;
    @XmlElement(name = "ResultLimitParam")
    protected int resultLimitParam;
    @XmlElement(name = "FromOutside")
    protected boolean fromOutside;
    @XmlElement(name = "IncludeSanctions")
    protected boolean includeSanctions;

    /**
     * Gets the value of the licNum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLicNum() {
        return licNum;
    }

    /**
     * Sets the value of the licNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLicNum(String value) {
        this.licNum = value;
    }

    /**
     * Gets the value of the date1 property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDate1() {
        return date1;
    }

    /**
     * Sets the value of the date1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDate1(XMLGregorianCalendar value) {
        this.date1 = value;
    }

    /**
     * Gets the value of the date2 property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDate2() {
        return date2;
    }

    /**
     * Sets the value of the date2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDate2(XMLGregorianCalendar value) {
        this.date2 = value;
    }

    /**
     * Gets the value of the viewDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getViewDate() {
        return viewDate;
    }

    /**
     * Sets the value of the viewDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setViewDate(XMLGregorianCalendar value) {
        this.viewDate = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the adr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAdr() {
        return adr;
    }

    /**
     * Sets the value of the adr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAdr(String value) {
        this.adr = value;
    }

    /**
     * Gets the value of the uori property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUori() {
        return uori;
    }

    /**
     * Sets the value of the uori property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUori(String value) {
        this.uori = value;
    }

    /**
     * Gets the value of the code property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getCode() {
        return code;
    }

    /**
     * Sets the value of the code property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setCode(BigDecimal value) {
        this.code = value;
    }

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStatus(String value) {
        this.status = value;
    }

    /**
     * Gets the value of the resultLimitParam property.
     * 
     */
    public int getResultLimitParam() {
        return resultLimitParam;
    }

    /**
     * Sets the value of the resultLimitParam property.
     * 
     */
    public void setResultLimitParam(int value) {
        this.resultLimitParam = value;
    }

    /**
     * Gets the value of the fromOutside property.
     * 
     */
    public boolean isFromOutside() {
        return fromOutside;
    }

    /**
     * Sets the value of the fromOutside property.
     * 
     */
    public void setFromOutside(boolean value) {
        this.fromOutside = value;
    }

    /**
     * Gets the value of the includeSanctions property.
     * 
     */
    public boolean isIncludeSanctions() {
        return includeSanctions;
    }

    /**
     * Sets the value of the includeSanctions property.
     * 
     */
    public void setIncludeSanctions(boolean value) {
        this.includeSanctions = value;
    }

}
