//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.07.13 at 04:55:54 PM EEST 
//


package com.dkey.customs.soapmeta;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.dkey.customs.soapmeta package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.dkey.customs.soapmeta
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetBrokListDS }
     * 
     */
    public GetBrokListDS createGetBrokListDS() {
        return new GetBrokListDS();
    }

    /**
     * Create an instance of {@link GetBrokListReq }
     * 
     */
    public GetBrokListReq createGetBrokListReq() {
        return new GetBrokListReq();
    }

    /**
     * Create an instance of {@link GetBrokListDSResponse }
     * 
     */
    public GetBrokListDSResponse createGetBrokListDSResponse() {
        return new GetBrokListDSResponse();
    }

    /**
     * Create an instance of {@link GetBrokListResponse }
     * 
     */
    public GetBrokListResponse createGetBrokListResponse() {
        return new GetBrokListResponse();
    }

    /**
     * Create an instance of {@link GetBrokListingDs }
     * 
     */
    public GetBrokListingDs createGetBrokListingDs() {
        return new GetBrokListingDs();
    }

    /**
     * Create an instance of {@link GetBrokListingDsResponse }
     * 
     */
    public GetBrokListingDsResponse createGetBrokListingDsResponse() {
        return new GetBrokListingDsResponse();
    }

    /**
     * Create an instance of {@link GetBrokListingForDomkDs }
     * 
     */
    public GetBrokListingForDomkDs createGetBrokListingForDomkDs() {
        return new GetBrokListingForDomkDs();
    }

    /**
     * Create an instance of {@link GetBrokListingForDomkReq }
     * 
     */
    public GetBrokListingForDomkReq createGetBrokListingForDomkReq() {
        return new GetBrokListingForDomkReq();
    }

    /**
     * Create an instance of {@link GetBrokListingForDomkDsResponse }
     * 
     */
    public GetBrokListingForDomkDsResponse createGetBrokListingForDomkDsResponse() {
        return new GetBrokListingForDomkDsResponse();
    }

    /**
     * Create an instance of {@link GetBrokListExt }
     * 
     */
    public GetBrokListExt createGetBrokListExt() {
        return new GetBrokListExt();
    }

    /**
     * Create an instance of {@link GetBrokListReq2 }
     * 
     */
    public GetBrokListReq2 createGetBrokListReq2() {
        return new GetBrokListReq2();
    }

    /**
     * Create an instance of {@link GetBrokListExtResponse }
     * 
     */
    public GetBrokListExtResponse createGetBrokListExtResponse() {
        return new GetBrokListExtResponse();
    }

    /**
     * Create an instance of {@link GetDocResponse }
     * 
     */
    public GetDocResponse createGetDocResponse() {
        return new GetDocResponse();
    }

    /**
     * Create an instance of {@link GetBrokDS }
     * 
     */
    public GetBrokDS createGetBrokDS() {
        return new GetBrokDS();
    }

    /**
     * Create an instance of {@link GetBrokDsReq }
     * 
     */
    public GetBrokDsReq createGetBrokDsReq() {
        return new GetBrokDsReq();
    }

    /**
     * Create an instance of {@link GetBrokDSResponse }
     * 
     */
    public GetBrokDSResponse createGetBrokDSResponse() {
        return new GetBrokDSResponse();
    }

    /**
     * Create an instance of {@link GetXMLResponse }
     * 
     */
    public GetXMLResponse createGetXMLResponse() {
        return new GetXMLResponse();
    }

    /**
     * Create an instance of {@link CancellBrokLic }
     * 
     */
    public CancellBrokLic createCancellBrokLic() {
        return new CancellBrokLic();
    }

    /**
     * Create an instance of {@link CancellBrokLicReq }
     * 
     */
    public CancellBrokLicReq createCancellBrokLicReq() {
        return new CancellBrokLicReq();
    }

    /**
     * Create an instance of {@link CancellBrokLicResponse }
     * 
     */
    public CancellBrokLicResponse createCancellBrokLicResponse() {
        return new CancellBrokLicResponse();
    }

    /**
     * Create an instance of {@link CancellBrokLicByGuid }
     * 
     */
    public CancellBrokLicByGuid createCancellBrokLicByGuid() {
        return new CancellBrokLicByGuid();
    }

    /**
     * Create an instance of {@link CancellBrokLicByGuidReq }
     * 
     */
    public CancellBrokLicByGuidReq createCancellBrokLicByGuidReq() {
        return new CancellBrokLicByGuidReq();
    }

    /**
     * Create an instance of {@link CancellBrokLicByGuidResponse }
     * 
     */
    public CancellBrokLicByGuidResponse createCancellBrokLicByGuidResponse() {
        return new CancellBrokLicByGuidResponse();
    }

    /**
     * Create an instance of {@link SaveBrok }
     * 
     */
    public SaveBrok createSaveBrok() {
        return new SaveBrok();
    }

    /**
     * Create an instance of {@link SaveBrokReq }
     * 
     */
    public SaveBrokReq createSaveBrokReq() {
        return new SaveBrokReq();
    }

    /**
     * Create an instance of {@link SaveBrokResponse }
     * 
     */
    public SaveBrokResponse createSaveBrokResponse() {
        return new SaveBrokResponse();
    }

    /**
     * Create an instance of {@link IsBrokLicExistsNew }
     * 
     */
    public IsBrokLicExistsNew createIsBrokLicExistsNew() {
        return new IsBrokLicExistsNew();
    }

    /**
     * Create an instance of {@link IsBrokLicExistsReq }
     * 
     */
    public IsBrokLicExistsReq createIsBrokLicExistsReq() {
        return new IsBrokLicExistsReq();
    }

    /**
     * Create an instance of {@link IsBrokLicExistsNewResponse }
     * 
     */
    public IsBrokLicExistsNewResponse createIsBrokLicExistsNewResponse() {
        return new IsBrokLicExistsNewResponse();
    }

    /**
     * Create an instance of {@link IsBrokLicExistsResp }
     * 
     */
    public IsBrokLicExistsResp createIsBrokLicExistsResp() {
        return new IsBrokLicExistsResp();
    }

    /**
     * Create an instance of {@link IsBrokLicExists }
     * 
     */
    public IsBrokLicExists createIsBrokLicExists() {
        return new IsBrokLicExists();
    }

    /**
     * Create an instance of {@link IsBrokLicExistsResponse }
     * 
     */
    public IsBrokLicExistsResponse createIsBrokLicExistsResponse() {
        return new IsBrokLicExistsResponse();
    }

    /**
     * Create an instance of {@link GetCliModified }
     * 
     */
    public GetCliModified createGetCliModified() {
        return new GetCliModified();
    }

    /**
     * Create an instance of {@link GetCliModifiedReq }
     * 
     */
    public GetCliModifiedReq createGetCliModifiedReq() {
        return new GetCliModifiedReq();
    }

    /**
     * Create an instance of {@link GetCliModifiedResponse }
     * 
     */
    public GetCliModifiedResponse createGetCliModifiedResponse() {
        return new GetCliModifiedResponse();
    }

    /**
     * Create an instance of {@link GetCliModifiedResp }
     * 
     */
    public GetCliModifiedResp createGetCliModifiedResp() {
        return new GetCliModifiedResp();
    }

    /**
     * Create an instance of {@link GetBrokPdf }
     * 
     */
    public GetBrokPdf createGetBrokPdf() {
        return new GetBrokPdf();
    }

    /**
     * Create an instance of {@link GetBrokPdfReq }
     * 
     */
    public GetBrokPdfReq createGetBrokPdfReq() {
        return new GetBrokPdfReq();
    }

    /**
     * Create an instance of {@link GetBrokPdfResponseEl }
     * 
     */
    public GetBrokPdfResponseEl createGetBrokPdfResponseEl() {
        return new GetBrokPdfResponseEl();
    }

    /**
     * Create an instance of {@link GetBrokPdfResponse }
     * 
     */
    public GetBrokPdfResponse createGetBrokPdfResponse() {
        return new GetBrokPdfResponse();
    }

    /**
     * Create an instance of {@link GetBrokAppPdf }
     * 
     */
    public GetBrokAppPdf createGetBrokAppPdf() {
        return new GetBrokAppPdf();
    }

    /**
     * Create an instance of {@link GetBrokAppPdfReq }
     * 
     */
    public GetBrokAppPdfReq createGetBrokAppPdfReq() {
        return new GetBrokAppPdfReq();
    }

    /**
     * Create an instance of {@link GetBrokAppPdfResponse }
     * 
     */
    public GetBrokAppPdfResponse createGetBrokAppPdfResponse() {
        return new GetBrokAppPdfResponse();
    }

    /**
     * Create an instance of {@link GetBrokAnalyticsNumbers }
     * 
     */
    public GetBrokAnalyticsNumbers createGetBrokAnalyticsNumbers() {
        return new GetBrokAnalyticsNumbers();
    }

    /**
     * Create an instance of {@link GetBrokAnalyticsNumbersReq }
     * 
     */
    public GetBrokAnalyticsNumbersReq createGetBrokAnalyticsNumbersReq() {
        return new GetBrokAnalyticsNumbersReq();
    }

    /**
     * Create an instance of {@link GetBrokAnalyticsNumbersResponse }
     * 
     */
    public GetBrokAnalyticsNumbersResponse createGetBrokAnalyticsNumbersResponse() {
        return new GetBrokAnalyticsNumbersResponse();
    }

    /**
     * Create an instance of {@link GetBrokAnalyticsNumbersResp }
     * 
     */
    public GetBrokAnalyticsNumbersResp createGetBrokAnalyticsNumbersResp() {
        return new GetBrokAnalyticsNumbersResp();
    }

    /**
     * Create an instance of {@link GetBrokStatusDc }
     * 
     */
    public GetBrokStatusDc createGetBrokStatusDc() {
        return new GetBrokStatusDc();
    }

    /**
     * Create an instance of {@link GetBrokStatusDcReq }
     * 
     */
    public GetBrokStatusDcReq createGetBrokStatusDcReq() {
        return new GetBrokStatusDcReq();
    }

    /**
     * Create an instance of {@link GetBrokStatusDcResponse }
     * 
     */
    public GetBrokStatusDcResponse createGetBrokStatusDcResponse() {
        return new GetBrokStatusDcResponse();
    }

    /**
     * Create an instance of {@link CsnWsRequestArgAuth }
     * 
     */
    public CsnWsRequestArgAuth createCsnWsRequestArgAuth() {
        return new CsnWsRequestArgAuth();
    }

    /**
     * Create an instance of {@link CsnWs2ResponseBase }
     * 
     */
    public CsnWs2ResponseBase createCsnWs2ResponseBase() {
        return new CsnWs2ResponseBase();
    }

    /**
     * Create an instance of {@link ArrayOfBrokAnalyticsCancellStatusNumbersItem }
     * 
     */
    public ArrayOfBrokAnalyticsCancellStatusNumbersItem createArrayOfBrokAnalyticsCancellStatusNumbersItem() {
        return new ArrayOfBrokAnalyticsCancellStatusNumbersItem();
    }

    /**
     * Create an instance of {@link BrokAnalyticsCancellStatusNumbersItem }
     * 
     */
    public BrokAnalyticsCancellStatusNumbersItem createBrokAnalyticsCancellStatusNumbersItem() {
        return new BrokAnalyticsCancellStatusNumbersItem();
    }

}
