//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.07.13 at 04:55:54 PM EEST 
//


package com.dkey.customs.soapmeta;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SaveBrokReq complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SaveBrokReq"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://tempuri.org/}CsnWsRequestArgBase"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="DataSet" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="IsAutomat" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="SEndMail" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SaveBrokReq", propOrder = {
    "dataSet",
    "isAutomat",
    "sEndMail"
})
public class SaveBrokReq
    extends CsnWsRequestArgBase
{

    @XmlElement(name = "DataSet")
    protected String dataSet;
    @XmlElement(name = "IsAutomat")
    protected boolean isAutomat;
    @XmlElement(name = "SEndMail")
    protected boolean sEndMail;

    /**
     * Gets the value of the dataSet property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDataSet() {
        return dataSet;
    }

    /**
     * Sets the value of the dataSet property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDataSet(String value) {
        this.dataSet = value;
    }

    /**
     * Gets the value of the isAutomat property.
     * 
     */
    public boolean isIsAutomat() {
        return isAutomat;
    }

    /**
     * Sets the value of the isAutomat property.
     * 
     */
    public void setIsAutomat(boolean value) {
        this.isAutomat = value;
    }

    /**
     * Gets the value of the sEndMail property.
     * 
     */
    public boolean isSEndMail() {
        return sEndMail;
    }

    /**
     * Sets the value of the sEndMail property.
     * 
     */
    public void setSEndMail(boolean value) {
        this.sEndMail = value;
    }

}
